name: Publish new version
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: install
      - name: Set versions and archive
        run: python ./.github/workflows/release.py ${{ github.event.release.tag_name }}
      - name: Upload .zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mudlet-release.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload info.json
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: info.json
          tag: ${{ github.ref }}
          overwrite: true
      